### ISSUE TITLE
Latence

### ISSUE THREAD

**Issue by Paradox222** [Triskaaa/UtilityZ#1]
le bot est vraiment bien mais c'est dommage qu'il a beaucoup de latence genre quand je fais des commandes il envois l'embed 5 sec apres (ma co ne bug pas)

**Comment by Triskaaa** [comment]
Hey,
Merci pour ton commentaire ! Le bot est surement plus lent si tu le lance en local sur ton pc vu que c'est un gros bot, mais sur replit ou un serveur dédié ca devrait être plus rapide. Le bot est écrit sur une version ancienne (et un peu buggé ^^') de Aoijs, alors c'est possible que ca soit ca... Si t'as d'autres problèmes, n'hésite pas a me MP sur Discord : Triskaaa#9999 ;)
